feat(PL-2372): use catalog configs for release rendering
nestoca/joy-generator pull request #5
Opened 2024-02-13 20:08 UTC by davidmdm

This PR changes the rendering of joy releases to use joy's SDK rendering which takes into account catalog configurations such as:
- valueMapping(s)
- defaultChart

The goal of these changes is to be able to remove nesto specific configuration from the appset and have it be directly configurable via the joy catalog.

## Default Chart from catalog being injected
<img width="577" alt="image" src="https://github.com/nestoca/joy-generator/assets/12768642/dc5fc7d1-c21f-447c-962b-4242605bf5c4">

## Annotation being mapped in from valueMapping
<img width="336" alt="image" src="https://github.com/nestoca/joy-generator/assets/12768642/fed06f14-127f-49cd-8160-45cbda43bde9">

## Image tag being mapped in from valueMapping
<img width="294" alt="image" src="https://github.com/nestoca/joy-generator/assets/12768642/64d00a33-5a00-4439-ae14-1c223b4013ea">

2024-02-14 16:35 UTC, riclima approved these changes

2024-02-14 18:52 UTC, riclima approved these changes

2024-02-14 21:55 UTC, ayahajar approved these changes

2024-02-15 18:57 UTC, alexstojda requested changes
Looks good so far, just some minor things & a question.

Please also add some comments for the new code since it was not clear at first glance why you extracted some code into a different method, as well as what the purpose of that code is.

2024-02-15 18:57 UTC, alexstojda commented on internal/apiserver/apiserver.go
> +func (server *ApiServer) Run() error {
By convention, receiver names should generally by 1-2 characters. Makes receiver variables easy to differentiate from other variables. 

You also change it here, but not in other functions. So lets just keep it as `s`

From go.dev: https://go.dev/wiki/CodeReviewComments#receiver-names

2024-02-15 18:57 UTC, alexstojda commented on internal/apiserver/apiserver.go
> +func (server *ApiServer) GetParamsExecute(c *gin.Context) {
See receiver naming comment above

2024-02-15 18:57 UTC, alexstojda commented on internal/generator/generator.go
> +		return &JoyContext{Catalog: cat, Config: cfg}, nil
Is this extraction to make the generator code testable?

2024-02-19 15:14 UTC, alexstojda approved these changes

2024-02-19 15:15 UTC, merged